const { SquareClient, SquareEnvironment } = require('square');
const { randomUUID } = require('crypto');
const { pool } = require('../db/pool');

const squareClient = new SquareClient({
  token: process.env.SQUARE_ACCESS_TOKEN,
  environment: process.env.SQUARE_ENV === 'production' ? SquareEnvironment.Production : SquareEnvironment.Sandbox,
});

/**
 * Square's model differs from Stripe's PaymentIntent flow: instead of
 * a client_secret confirmed in the browser, Square typically takes a
 * payment source (nonce/token) generated by the Web Payments SDK on
 * the frontend and charges it in one call. This creates that charge
 * against the batch total, computed server-side same as Stripe.
 */
async function createSquarePayment(billingBatchId, sourceId) {
  if (!sourceId) {
    throw new Error('sourceId (from Square Web Payments SDK) is required');
  }

  const totalRes = await pool.query(
    `SELECT COALESCE(SUM(woli.quantity_calculated * woli.unit_price_charged), 0) AS total
     FROM work_orders wo
     JOIN work_order_line_items woli ON woli.work_order_id = wo.id
     WHERE wo.billing_batch_id = $1`,
    [billingBatchId]
  );
  const totalAmount = Number(totalRes.rows[0].total);
  if (totalAmount <= 0) {
    throw new Error('Billing batch has no billable total — cannot charge $0');
  }

  const response = await squareClient.payments.create({
    sourceId,
    idempotencyKey: randomUUID(), // Square's own idempotency guard, same principle as processed_webhooks
    amountMoney: {
      amount: BigInt(Math.round(totalAmount * 100)),
      currency: 'USD',
    },
  });

  const payment = response.payment;

  await pool.query(
    `INSERT INTO payments (billing_batch_id, provider, provider_reference_id, amount, status, completed_at)
     VALUES ($1, 'square', $2, $3, $4, CASE WHEN $4 = 'succeeded' THEN NOW() ELSE NULL END)`,
    [billingBatchId, payment.id, totalAmount, payment.status === 'COMPLETED' ? 'succeeded' : 'pending']
  );

  if (payment.status === 'COMPLETED') {
    await pool.query(`UPDATE billing_batches SET batch_status = 'closed' WHERE id = $1`, [billingBatchId]);
  }

  return { paymentId: payment.id, status: payment.status, amount: totalAmount };
}

module.exports = { createSquarePayment };
